### ISSUE TITLE
Index mappings do not include all of the fields needed for this sample dashboard

### ISSUE THREAD

**Issue by aburkleaux-amazon** [aws-samples/aws-media-services-vod-automation#2]
When importing the sample dashboard into Kibana there are errors.  I think the index mappings need to be updated to include the missing values.  

Saved Objects: Importing Average Standby Time by Queue (02cf4fd0-4ce6-11e8-b9a5-055667df0bb6) failed: Could not locate that index-pattern-field (id: progressMetrics.queuedDuration)

Saved Objects: Importing Job count by userMetadata:workflow (d3737070-4d5f-11e8-b9a5-055667df0bb6) failed: Could not locate that index-pattern-field (id: filters.jobId.keyword)

Saved Objects: Importing Avg Decode Rate by Queue (f6fc3060-4d5d-11e8-b9a5-055667df0bb6) failed: Could not locate that index-pattern-field (id: progressMetrics.decodeRate)

Saved Objects: Importing Progressing Jobs by Queue (58e6a180-4d67-11e8-b9a5-055667df0bb6) failed: Could not locate that index-pattern-field (id: filters.jobId.keyword)

Saved Objects: Importing Job Detail (474ecb00-4d62-11e8-b9a5-055667df0bb6) failed: Could not locate that index-pattern-field (id: filters.queueName.keyword)

**Comment by morjoan** [comment]
If you run jobs after the elasticsearch CloudFormation has been fully deployed, before importing the dashboard, then these errors don't pop up. 
I also uploaded a new sample dashboard that incorporates the new job metrics available from MediaConvert. 
Closing this for now.
