### ISSUE TITLE
AWS Mediaconvert added job progress metrics: currentPhase and jobPercentComplete in the "MediaConvert Job State Change" event

### ISSUE THREAD

**Issue by aburkleaux-amazon** [aws-samples/aws-media-services-vod-automation#3]
Semantics of the new metrics are in documented in the AWS Elemental Mediaconvert API reference: https://docs.aws.amazon.com/mediaconvert/latest/apireference/jobs.html.

This project should use the new metrics.

**Comment by morjoan** [comment]
These are now incorporated into the project.
