### ISSUE TITLE
Knowing the Way

### ISSUE THREAD

**Issue by davidbitton** [aws-samples/aws-media-services-vod-automation#4]
What is the true path one should follow for VOD? Is it this repo, or is https://github.com/awslabs/video-on-demand-on-aws?

**Comment by morjoan** [comment]
Please use the VOD on AWS solution for running transcoding jobs/transcoding workflows. The repo here is meant to be a tutorial on how to automate MediaConvert jobs. The progress and monitoring tools in this repo can be used in conjunction with your VOD workflows using the VOD on AWS solution.
